### ISSUE TITLE
Cast column_default to string

### ISSUE THREAD

**Issue by olavloite** [cloudspannerecosystem/sqltools-cloud-spanner-driver#13]
Any query that references the `information_schema.columns.column_default` column should cast the value to string: https://github.com/cloudspannerecosystem/sqltools-cloud-spanner-driver/blob/bc115d6a00bc3cfc6d62e13014b311ab73360ad9/src/ls/queries.ts#L42

cc @dttran

**Comment by dttran** [comment]
We'd need to prioritize this change. This is blocking a Spanner feature from being released.
