### ISSUE TITLE
Connecting to the spanner emulator

### ISSUE THREAD

**Issue by jankleinert** [cloudspannerecosystem/sqltools-cloud-spanner-driver#6]
I'm trying to determine if this can be used with the spanner emulator. I don't see a setting or other way of specifying that it should use the emulator. Is it possible?

**Comment by olavloite** [comment]
It is possible, but I think there's room for improvement in how easy it is. The current procedure would be:
1. Set the environment variable `SPANNER_EMULATOR_HOST=localhost:9010`.
2. Start the emulator.
3. Create an instance and database on the emulator named `test-instance` and `test-database` (for example through gcloud CLI).
4. Start Visual Studio Code and create a new connection in the normal way. Use `test-project`, `test-instance` and `test-database` as values for Project, Instance and Database. Credentials are not needed.
5. Click Connect.

I've confirmed that the above procedure works. Note that if Visual Studio Code was already running before you set the environment variable, then you will need to restart VS Code.

A possible improvement here would be to add an explicit option to the VS Code connector to automatically configure the connection for the emulator. We did that [recently for Java as well](https://github.com/googleapis/java-spanner/pull/931), and it was mainly intended for generic tools and frameworks that connect to Spanner through JDBC. That would make connecting to the emulator a lot easier, as it would:
1. Remove the need to set the environment variable `SPANNER_EMULATOR_HOST`, which impacts the entire environment of the user (all connections to Spanner will look for this env var).
2. Remove the need to manually create an instance and database on the emulator.
3. The need to restart VS Code if it was already running before you set the env var.

**Comment by jankleinert** [comment]
Ah, thank you! It was the step to restart VS Code that I was missing.

**Comment by jankleinert** [comment]
@olavloite Do you know when these changes will be available in the VS Code marketplace? The current version there has a Change Log showing only a single initial release from 3/16

**Comment by jankleinert** [comment]
Disregard - I see now that there's a new release, it's just not reflected in the changelog. That would be nice to update, if possible!

**Comment by olavloite** [comment]
> Disregard - I see now that there's a new release, it's just not reflected in the changelog. That would be nice to update, if possible!

Thanks for noticing that.

I've updated the readme and changelog to reflect the latest changes, but in order to update the Marketplace I need to push a new version. I have one additional feature that I would like to add (make the max 100,000 rows limit configurable), so I'll try to add it tomorrow instead of placing a new version just for updating the changelog.

**Comment by olavloite** [comment]
@jankleinert I've made the query limit configurable, updated the changelog and released a new version, so the updated changelog should now be visible in the marketplace for end users.
